version: '3.3'
services:
  db:
    image: mysql:5.7
    container_name: f1db
    command: mysqld --sql_mode=""
    restart: unless-stopped
    env_file: .env
    ports:
      - '${MYSQL_LOCAL_PORT}:${MYSQL_DOCKER_PORT}'
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
volumes:
  db: