name: Java CI with Maven
on:
  push:
    branches:
      - main
      - task1
      - task2
  pull_request:
    branches:
      - main
      - task1
      - task2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17-ea'
          distribution: 'temurin'
          cache: maven
      - name: Compile
        run: mvn compile --file pom.xml
      - name: Build
        run: mvn install --file pom.xml
      - name: Run tests
        run: mvn test --file pom.xml